# Generated by Django 3.2.7 on 2021-09-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetwo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='stage_1',
            name='level',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='stagetwo',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
