# Generated by Django 3.2.7 on 2021-09-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210913_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage_1',
            name='format',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stagetwo',
            name='format',
            field=models.TextField(blank=True),
        ),
    ]
