# Generated by Django 3.2.7 on 2021-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210926_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage_1',
            name='format',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stagetwo',
            name='format',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
