# Generated by Django 3.2.7 on 2021-09-12 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('last_submit', models.DateTimeField(default=datetime.datetime(2021, 9, 13, 0, 7, 16, 809489))),
                ('question_level', models.IntegerField(default=1)),
                ('level2', models.IntegerField(default=-2)),
                ('count2', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDetails',
            fields=[
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.player')),
                ('full_name', models.CharField(default='your name', max_length=400)),
                ('college', models.CharField(default='none', max_length=400)),
                ('year', models.CharField(default='1', max_length=10)),
                ('contact', models.BigIntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StageOneHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, default=0)),
                ('taken', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.player')),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_on', models.IntegerField(blank=True, default=0)),
                ('solved', models.BooleanField(default=False)),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.player')),
            ],
        ),
    ]
