# Generated by Django 3.2.7 on 2021-09-12 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 0, 17, 1, 46258)),
        ),
    ]
