# Generated by Django 3.2.7 on 2021-09-16 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_player_last_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 21, 55, 55, 530523)),
        ),
    ]
