# Generated by Django 3.2.7 on 2021-09-26 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_player_last_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 26, 22, 41, 14, 168113)),
        ),
    ]
