# Generated by Django 3.2.7 on 2021-09-04 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20210902_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 21, 33, 52, 534079)),
        ),
    ]
